version: '3.8'

services:
  server:
    build:
      context: .
      target: final
    ports:
      - 8081:8080
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ConnectionStrings__DefaultConnection=Server=${DB_HOST};Port=${DB_PORT};Database=${DB_NAME};User=${DB_USER};Password=${DB_PASSWORD};
      - ConnectionStrings__AlgoDbConnection=Server=${DB_HOST};Port=${DB_PORT};Database=${ALGO_DB_NAME};User=${DB_USER};Password=${DB_PASSWORD};

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - 3307:3306
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

volumes:
  db-data:
